import { StyleSheet } from 'react-native';

export const welcomeStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    backgroundImage: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    gradientOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    floatingElements: {
        ...StyleSheet.absoluteFillObject,
    },
    floatingIcon: {
        position: 'absolute',
        padding: 15,
    },
    icon1: {
        top: 80,
        left: 20,
    },
    icon2: {
        top: 150,
        right: 30,
    },
    icon3: {
        bottom: 200,
        left: 15,
    },
    icon4: {
        bottom: 250,
        right: 40,
    },
    icon5: {
        top: 200,
        left: 50,
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 30,
        paddingTop: 60,
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: 40,
    },
    logoBackground: {
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: '#2196F3', 
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.3,
        shadowRadius: 25,
        elevation: 15,
        borderWidth: 3,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    logoContent: {
        position: 'relative',
        width: 100,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
    },
    rocketWrapper: {
        position: 'absolute',
        top: 0,
        left: 10,
        zIndex: 2,
    },
    chartWrapper: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        zIndex: 1,
    },
    chartLine: {
        position: 'absolute',
        bottom: 15,
        right: 35,
        flexDirection: 'row',
        alignItems: 'flex-end',
        width: 30,
        height: 15,
    },
    chartPoint1: {
        width: 3,
        height: 8,
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        marginRight: 2,
    },
    chartPoint2: {
        width: 3,
        height: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        marginRight: 2,
    },
    chartPoint3: {
        width: 3,
        height: 15,
        backgroundColor: '#FFFFFF',
    },
    arrowIcon: {
        position: 'absolute',
        bottom: -5,
        right: 0,
    },
    rocketContainer: {
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'center',
    },
    chartIcon: {
        position: 'absolute',
        bottom: -5,
        right: -5,
        backgroundColor: 'rgba(33, 150, 243, 0.8)',
        borderRadius: 15,
        padding: 5,
    },
    logoRing: {
        position: 'absolute',
        width: 160,
        height: 160,
        borderRadius: 80,
        borderWidth: 3,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        borderStyle: 'dashed',
    },
    titleContainer: {
        alignItems: 'center',
        marginBottom: 40,
    },
    mainTitle: {
        fontSize: 52,
        fontWeight: 'bold',
        color: '#FFFFFF',
        textAlign: 'center',
        marginBottom: 12,
        textShadowColor: 'rgba(0, 0, 0, 0.4)',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 10,
        letterSpacing: 3,
    },
    subtitle: {
        fontSize: 18,
        color: 'rgba(255, 255, 255, 0.95)',
        textAlign: 'center',
        marginBottom: 18,
        fontWeight: '600',
        letterSpacing: 1.5,
    },
    description: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.85)',
        textAlign: 'center',
        lineHeight: 26,
        paddingHorizontal: 15,
        fontWeight: '400',
    },
    featuresContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginBottom: 35,
        paddingHorizontal: 10,
    },
    feature: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        paddingVertical: 18,
        paddingHorizontal: 22,
        borderRadius: 25,
        minWidth: 85,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    featureText: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '600',
        marginTop: 8,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 30,
        marginBottom: 40,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    stat: {
        alignItems: 'center',
        paddingHorizontal: 15,
    },
    statNumber: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    statLabel: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.8)',
        marginTop: 4,
    },
    statDivider: {
        width: 1,
        height: 40,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    buttonContainer: {
        width: '100%',
        alignItems: 'center',
    },
    button: {
        width: '100%',
        marginBottom: 15,
        borderRadius: 30,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.4,
        shadowRadius: 20,
        elevation: 12,
    },
    buttonGradient: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 35,
    },
    buttonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1565C0',
        marginRight: 10,
    },
    buttonIcon: {
        marginLeft: 5,
    },
    secondaryButton: {
        paddingVertical: 15,
        paddingHorizontal: 30,
    },
    secondaryButtonText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 16,
        textAlign: 'center',
        textDecorationLine: 'underline',
    },
    bottomIndicators: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 40,
        gap: 10,
    },
    indicatorDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
    },
    activeDot: {
        backgroundColor: '#FFFFFF',
        width: 28,
        borderRadius: 14,
    },
});
